#ifndef __MNH_TRACE_
#define __MNH_TRACE_


#define MNH_TRACE_SETUP_PROCESSOR	0x100
#define MNH_TRACE_MAIN_BANNER		0x600
#define MNH_TRACE_MAIN_END		0x601
#define MNH_TRACE_KERNEL_INIT		0x700
#define MNH_TRACE_INIT_RUNNING		0x701
#define MNH_TRACE_PCIE_PROBE		0x800
#define MNH_TRACE_PCIE_PROBE_DONE	0x801
#define MNH_TRACE_PAINTBOX_PROBE	0x900
#define MNH_TRACE_PAINTBOX_PROBE_DONE	0x901
#define MNH_TRACE_EASELCOMM_INIT	0xa00
#define MNH_TRACE_EASELCOMM_INIT_DONE	0xa01

void mnh_trace(uint32_t value);

#endif /* __MNH_TRACE_ */

