/* auto generated: Wednesday, August 17th, 2016 6:17:55pm */
/*
 * Copyright (c) 2016, Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of Intel nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __MNH_HWIO_PRMU_
#define __MNH_HWIO_PRMU_

#define HWIO_PRMU_READ_CTRL_REGOFF 0x0
#define HWIO_PRMU_READ_CTRL_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_READ_CTRL_REGOFF)
#define HWIO_PRMU_READ_CTRL_RSVD0_FLDMASK (0xffe00000)
#define HWIO_PRMU_READ_CTRL_RSVD0_FLDSHFT (21)
#define HWIO_PRMU_READ_CTRL_RD_REQ_TOTAL_BYTE_CNT_CLR_FLDMASK (0x100000)
#define HWIO_PRMU_READ_CTRL_RD_REQ_TOTAL_BYTE_CNT_CLR_FLDSHFT (20)
#define HWIO_PRMU_READ_CTRL_RD_RESP_CNT_CLR_FLDMASK (0x80000)
#define HWIO_PRMU_READ_CTRL_RD_RESP_CNT_CLR_FLDSHFT (19)
#define HWIO_PRMU_READ_CTRL_RD_REQ_CNT_CLR_FLDMASK (0x40000)
#define HWIO_PRMU_READ_CTRL_RD_REQ_CNT_CLR_FLDSHFT (18)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RESP_CLR_FLDMASK (0x20000)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RESP_CLR_FLDSHFT (17)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RDY_CLR_FLDMASK (0x10000)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RDY_CLR_FLDSHFT (16)
#define HWIO_PRMU_READ_CTRL_RSVD1_FLDMASK (0xffe0)
#define HWIO_PRMU_READ_CTRL_RSVD1_FLDSHFT (5)
#define HWIO_PRMU_READ_CTRL_RD_REQ_TOTAL_BYTE_CNT_EN_FLDMASK (0x10)
#define HWIO_PRMU_READ_CTRL_RD_REQ_TOTAL_BYTE_CNT_EN_FLDSHFT (4)
#define HWIO_PRMU_READ_CTRL_RD_RESP_CNT_EN_FLDMASK (0x8)
#define HWIO_PRMU_READ_CTRL_RD_RESP_CNT_EN_FLDSHFT (3)
#define HWIO_PRMU_READ_CTRL_RD_REQ_CNT_EN_FLDMASK (0x4)
#define HWIO_PRMU_READ_CTRL_RD_REQ_CNT_EN_FLDSHFT (2)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RESP_EN_FLDMASK (0x2)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RESP_EN_FLDSHFT (1)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RDY_EN_FLDMASK (0x1)
#define HWIO_PRMU_READ_CTRL_RD_REQ2RDY_EN_FLDSHFT (0)

#define HWIO_PRMU_WRITE_CTRL_REGOFF 0x4
#define HWIO_PRMU_WRITE_CTRL_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WRITE_CTRL_REGOFF)
#define HWIO_PRMU_WRITE_CTRL_RSVD0_FLDMASK (0xffe00000)
#define HWIO_PRMU_WRITE_CTRL_RSVD0_FLDSHFT (21)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_TOTAL_BYTE_CNT_CLR_FLDMASK (0x100000)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_TOTAL_BYTE_CNT_CLR_FLDSHFT (20)
#define HWIO_PRMU_WRITE_CTRL_WR_RESP_CNT_CLR_FLDMASK (0x80000)
#define HWIO_PRMU_WRITE_CTRL_WR_RESP_CNT_CLR_FLDSHFT (19)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_CNT_CLR_FLDMASK (0x40000)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_CNT_CLR_FLDSHFT (18)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RESP_CLR_FLDMASK (0x20000)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RESP_CLR_FLDSHFT (17)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RDY_CLR_FLDMASK (0x10000)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RDY_CLR_FLDSHFT (16)
#define HWIO_PRMU_WRITE_CTRL_RSVD1_FLDMASK (0xffe0)
#define HWIO_PRMU_WRITE_CTRL_RSVD1_FLDSHFT (5)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_TOTAL_BYTE_CNT_EN_FLDMASK (0x10)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_TOTAL_BYTE_CNT_EN_FLDSHFT (4)
#define HWIO_PRMU_WRITE_CTRL_WR_RESP_CNT_EN_FLDMASK (0x8)
#define HWIO_PRMU_WRITE_CTRL_WR_RESP_CNT_EN_FLDSHFT (3)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_CNT_EN_FLDMASK (0x4)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ_CNT_EN_FLDSHFT (2)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RESP_EN_FLDMASK (0x2)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RESP_EN_FLDSHFT (1)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RDY_EN_FLDMASK (0x1)
#define HWIO_PRMU_WRITE_CTRL_WR_REQ2RDY_EN_FLDSHFT (0)

#define HWIO_PRMU_IRQ_EN_REGOFF 0x8
#define HWIO_PRMU_IRQ_EN_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_IRQ_EN_REGOFF)
#define HWIO_PRMU_IRQ_EN_RSVD0_FLDMASK (0xffffffc0)
#define HWIO_PRMU_IRQ_EN_RSVD0_FLDSHFT (6)
#define HWIO_PRMU_IRQ_EN_WR_RESP_CNT_OVFL_IE_FLDMASK (0x20)
#define HWIO_PRMU_IRQ_EN_WR_RESP_CNT_OVFL_IE_FLDSHFT (5)
#define HWIO_PRMU_IRQ_EN_WR_REQ_CNT_OVFL_IE_FLDMASK (0x10)
#define HWIO_PRMU_IRQ_EN_WR_REQ_CNT_OVFL_IE_FLDSHFT (4)
#define HWIO_PRMU_IRQ_EN_WR_REQ_TOTAL_BYTE_OVFL_IE_FLDMASK (0x8)
#define HWIO_PRMU_IRQ_EN_WR_REQ_TOTAL_BYTE_OVFL_IE_FLDSHFT (3)
#define HWIO_PRMU_IRQ_EN_RD_RESP_CNT_OVFL_IE_FLDMASK (0x4)
#define HWIO_PRMU_IRQ_EN_RD_RESP_CNT_OVFL_IE_FLDSHFT (2)
#define HWIO_PRMU_IRQ_EN_RD_REQ_CNT_OVFL_IE_FLDMASK (0x2)
#define HWIO_PRMU_IRQ_EN_RD_REQ_CNT_OVFL_IE_FLDSHFT (1)
#define HWIO_PRMU_IRQ_EN_RD_REQ_TOTAL_BYTE_OVFL_IE_FLDMASK (0x1)
#define HWIO_PRMU_IRQ_EN_RD_REQ_TOTAL_BYTE_OVFL_IE_FLDSHFT (0)

#define HWIO_PRMU_IRQ_STS_REGOFF 0x0C
#define HWIO_PRMU_IRQ_STS_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_IRQ_STS_REGOFF)
#define HWIO_PRMU_IRQ_STS_RSVD0_FLDMASK (0xffffffc0)
#define HWIO_PRMU_IRQ_STS_RSVD0_FLDSHFT (6)
#define HWIO_PRMU_IRQ_STS_WR_RESP_CNT_OVFL_STS_FLDMASK (0x20)
#define HWIO_PRMU_IRQ_STS_WR_RESP_CNT_OVFL_STS_FLDSHFT (5)
#define HWIO_PRMU_IRQ_STS_WR_REQ_CNT_OVFL_STS_FLDMASK (0x10)
#define HWIO_PRMU_IRQ_STS_WR_REQ_CNT_OVFL_STS_FLDSHFT (4)
#define HWIO_PRMU_IRQ_STS_WR_REQ_TOTAL_BYTE_OVFL_STS_FLDMASK (0x8)
#define HWIO_PRMU_IRQ_STS_WR_REQ_TOTAL_BYTE_OVFL_STS_FLDSHFT (3)
#define HWIO_PRMU_IRQ_STS_RD_RESP_CNT_OVFL_STS_FLDMASK (0x4)
#define HWIO_PRMU_IRQ_STS_RD_RESP_CNT_OVFL_STS_FLDSHFT (2)
#define HWIO_PRMU_IRQ_STS_RD_REQ_CNT_OVFL_STS_FLDMASK (0x2)
#define HWIO_PRMU_IRQ_STS_RD_REQ_CNT_OVFL_STS_FLDSHFT (1)
#define HWIO_PRMU_IRQ_STS_RD_REQ_TOTAL_BYTE_OVFL_STS_FLDMASK (0x1)
#define HWIO_PRMU_IRQ_STS_RD_REQ_TOTAL_BYTE_OVFL_STS_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_REGOFF 0x10
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_REGOFF)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_LAT_MIN_FLDMASK (0xffff0000)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_LAT_MIN_FLDSHFT (16)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_LAT_CUR_FLDMASK (0xffff)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_CUR_MIN_LAT_CUR_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_REGOFF 0x14
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_REGOFF)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_LAT_AVG_FLDMASK (0xffff0000)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_LAT_AVG_FLDSHFT (16)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_LAT_MAX_FLDMASK (0xffff)
#define HWIO_PRMU_RD_REQ2RDY_LATENCY_MAX_AVG_LAT_MAX_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_REGOFF 0x18
#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_REGOFF)
#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_RD_REQ2RDY_MIN_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_REGOFF 0x1C
#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_REGOFF)
#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_RD_REQ2RDY_MAX_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_REGOFF 0x20
#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_REGOFF)
#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_LAT_MIN_FLDMASK (0xffff0000)
#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_LAT_MIN_FLDSHFT (16)
#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_LAT_CUR_FLDMASK (0xffff)
#define HWIO_PRMU_REQ2RESP_LATENCY_CUR_MIN_LAT_CUR_FLDSHFT (0)

#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_REGOFF 0x24
#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_REGOFF)
#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_LAT_AVG_FLDMASK (0xffff0000)
#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_LAT_AVG_FLDSHFT (16)
#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_LAT_MAX_FLDMASK (0xffff)
#define HWIO_PRMU_REQ2RESP_LATENCY_MAX_AVG_LAT_MAX_FLDSHFT (0)

#define HWIO_PRMU_REQ2RESP_MIN_ADDR_REGOFF 0x28
#define HWIO_PRMU_REQ2RESP_MIN_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_REQ2RESP_MIN_ADDR_REGOFF)
#define HWIO_PRMU_REQ2RESP_MIN_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_REQ2RESP_MIN_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_REQ2RESP_MIN_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_REQ2RESP_MIN_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_REQ2RESP_MAX_ADDR_REGOFF 0x2C
#define HWIO_PRMU_REQ2RESP_MAX_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_REQ2RESP_MAX_ADDR_REGOFF)
#define HWIO_PRMU_REQ2RESP_MAX_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_REQ2RESP_MAX_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_REQ2RESP_MAX_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_REQ2RESP_MAX_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ_CNT_REGOFF 0x30
#define HWIO_PRMU_RD_REQ_CNT_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ_CNT_REGOFF)
#define HWIO_PRMU_RD_REQ_CNT_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_RD_REQ_CNT_CNT_FLDSHFT (0)

#define HWIO_PRMU_RD_RESP_CNT_REGOFF 0x34
#define HWIO_PRMU_RD_RESP_CNT_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_RESP_CNT_REGOFF)
#define HWIO_PRMU_RD_RESP_CNT_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_RD_RESP_CNT_CNT_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ_OUTSTANDING_REGOFF 0x38
#define HWIO_PRMU_RD_REQ_OUTSTANDING_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ_OUTSTANDING_REGOFF)
#define HWIO_PRMU_RD_REQ_OUTSTANDING_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_RD_REQ_OUTSTANDING_CNT_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_LO_REGOFF 0x3C
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_LO_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_LO_REGOFF)
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_LO_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_LO_CNT_FLDSHFT (0)

#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_HI_REGOFF 0x40
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_HI_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_HI_REGOFF)
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_HI_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_RD_REQ_TOTAL_BYTE_CNT_HI_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_REGOFF 0x44
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_REGOFF)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_LAT_MIN_FLDMASK (0xffff0000)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_LAT_MIN_FLDSHFT (16)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_LAT_CUR_FLDMASK (0xffff)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_CUR_MIN_LAT_CUR_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_REGOFF 0x48
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_REGOFF)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_LAT_AVG_FLDMASK (0xffff0000)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_LAT_AVG_FLDSHFT (16)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_LAT_MAX_FLDMASK (0xffff)
#define HWIO_PRMU_WR_REQ2RDY_LATENCY_MAX_AVG_LAT_MAX_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_REGOFF 0x4C
#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_REGOFF)
#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_WR_REQ2RDY_MIN_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_REGOFF 0x50
#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_REGOFF)
#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_WR_REQ2RDY_MAX_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_CNT_REGOFF 0x64
#define HWIO_PRMU_WR_REQ_CNT_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_CNT_REGOFF)
#define HWIO_PRMU_WR_REQ_CNT_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_CNT_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_RESP_CNT_REGOFF 0x68
#define HWIO_PRMU_WR_RESP_CNT_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_RESP_CNT_REGOFF)
#define HWIO_PRMU_WR_RESP_CNT_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_RESP_CNT_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_OUTSTANDING_REGOFF 0x6C
#define HWIO_PRMU_WR_REQ_OUTSTANDING_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_OUTSTANDING_REGOFF)
#define HWIO_PRMU_WR_REQ_OUTSTANDING_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_OUTSTANDING_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_LO_REGOFF 0x70
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_LO_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_LO_REGOFF)
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_LO_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_LO_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_HI_REGOFF 0x74
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_HI_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_HI_REGOFF)
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_HI_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_TOTAL_BYTE_CNT_HI_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_LO_REGOFF 0x78
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_LO_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_LO_REGOFF)
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_LO_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_LO_CNT_FLDSHFT (0)

#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_HI_REGOFF 0x7C
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_HI_ADDR(bAddr,regX) (bAddr + HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_HI_REGOFF)
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_HI_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_WR_REQ_ACTUAL_BYTE_CNT_HI_CNT_FLDSHFT (0)

#endif /* __MNH_HWIO_PRMU_ */
