/* auto generated: Wednesday, August 17th, 2016 6:17:55pm */
/*
 * Copyright (c) 2016, Intel Corporation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * Neither the name of Intel nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef __MNH_HWIO_PRMU_
#define __MNH_HWIO_PRMU_

#define HWIO_PRMU_RC_REGOFF 0x0
#define HWIO_PRMU_RC_ADDR(bAddr, regX) (bAddr + HWIO_PRMU_RC_REGOFF)
#define HWIO_PRMU_RC_RSVD0_FLDMASK (0xffe00000)
#define HWIO_PRMU_RC_RSVD0_FLDSHFT (21)
#define HWIO_PRMU_RC_RD_REQ_LEN_CNT_CLR_FLDMASK (0x100000)
#define HWIO_PRMU_RC_RD_REQ_LEN_CNT_CLR_FLDSHFT (20)
#define HWIO_PRMU_RC_RD_RESP_CNT_CLR_FLDMASK (0x80000)
#define HWIO_PRMU_RC_RD_RESP_CNT_CLR_FLDSHFT (19)
#define HWIO_PRMU_RC_RD_REQ_CNT_CLR_FLDMASK (0x40000)
#define HWIO_PRMU_RC_RD_REQ_CNT_CLR_FLDSHFT (18)
#define HWIO_PRMU_RC_RD_REQ_RESP_CLR_FLDMASK (0x20000)
#define HWIO_PRMU_RC_RD_REQ_RESP_CLR_FLDSHFT (17)
#define HWIO_PRMU_RC_RD_REQ_RDY_CLR_FLDMASK (0x10000)
#define HWIO_PRMU_RC_RD_REQ_RDY_CLR_FLDSHFT (16)
#define HWIO_PRMU_RC_RSVD1_FLDMASK (0xffe0)
#define HWIO_PRMU_RC_RSVD1_FLDSHFT (5)
#define HWIO_PRMU_RC_RD_REQ_LEN_CNT_EN_FLDMASK (0x10)
#define HWIO_PRMU_RC_RD_REQ_LEN_CNT_EN_FLDSHFT (4)
#define HWIO_PRMU_RC_RD_RESP_CNT_EN_FLDMASK (0x8)
#define HWIO_PRMU_RC_RD_RESP_CNT_EN_FLDSHFT (3)
#define HWIO_PRMU_RC_RD_REQ_CNT_EN_FLDMASK (0x4)
#define HWIO_PRMU_RC_RD_REQ_CNT_EN_FLDSHFT (2)
#define HWIO_PRMU_RC_RD_REQ_RESP_EN_FLDMASK (0x2)
#define HWIO_PRMU_RC_RD_REQ_RESP_EN_FLDSHFT (1)
#define HWIO_PRMU_RC_RD_REQ_RDY_EN_FLDMASK (0x1)
#define HWIO_PRMU_RC_RD_REQ_RDY_EN_FLDSHFT (0)

#define HWIO_PRMU_WC_REGOFF 0x4
#define HWIO_PRMU_WC_ADDR(bAddr, regX) (bAddr + HWIO_PRMU_WC_REGOFF)
#define HWIO_PRMU_WC_RSVD0_FLDMASK (0xffe00000)
#define HWIO_PRMU_WC_RSVD0_FLDSHFT (21)
#define HWIO_PRMU_WC_WR_REQ_LEN_CNT_CLR_FLDMASK (0x100000)
#define HWIO_PRMU_WC_WR_REQ_LEN_CNT_CLR_FLDSHFT (20)
#define HWIO_PRMU_WC_WR_RESP_CNT_CLR_FLDMASK (0x80000)
#define HWIO_PRMU_WC_WR_RESP_CNT_CLR_FLDSHFT (19)
#define HWIO_PRMU_WC_WR_REQ_CNT_CLR_FLDMASK (0x40000)
#define HWIO_PRMU_WC_WR_REQ_CNT_CLR_FLDSHFT (18)
#define HWIO_PRMU_WC_WR_REQ_RESP_CLR_FLDMASK (0x20000)
#define HWIO_PRMU_WC_WR_REQ_RESP_CLR_FLDSHFT (17)
#define HWIO_PRMU_WC_WR_REQ_RDY_CLR_FLDMASK (0x10000)
#define HWIO_PRMU_WC_WR_REQ_RDY_CLR_FLDSHFT (16)
#define HWIO_PRMU_WC_RSVD1_FLDMASK (0xffe0)
#define HWIO_PRMU_WC_RSVD1_FLDSHFT (5)
#define HWIO_PRMU_WC_WR_REQ_LEN_CNT_EN_FLDMASK (0x10)
#define HWIO_PRMU_WC_WR_REQ_LEN_CNT_EN_FLDSHFT (4)
#define HWIO_PRMU_WC_WR_RESP_CNT_EN_FLDMASK (0x8)
#define HWIO_PRMU_WC_WR_RESP_CNT_EN_FLDSHFT (3)
#define HWIO_PRMU_WC_WR_REQ_CNT_EN_FLDMASK (0x4)
#define HWIO_PRMU_WC_WR_REQ_CNT_EN_FLDSHFT (2)
#define HWIO_PRMU_WC_WR_REQ_RESP_EN_FLDMASK (0x2)
#define HWIO_PRMU_WC_WR_REQ_RESP_EN_FLDSHFT (1)
#define HWIO_PRMU_WC_WR_REQ_RDY_EN_FLDMASK (0x1)
#define HWIO_PRMU_WC_WR_REQ_RDY_EN_FLDSHFT (0)

#define HWIO_PRMU_IE_REGOFF 0x8
#define HWIO_PRMU_IE_ADDR(bAddr, regX) (bAddr + HWIO_PRMU_IE_REGOFF)
#define HWIO_PRMU_IE_RSVD0_FLDMASK (0xffffffc0)
#define HWIO_PRMU_IE_RSVD0_FLDSHFT (6)
#define HWIO_PRMU_IE_WR_RESP_CNT_OVFL_EN_FLDMASK (0x20)
#define HWIO_PRMU_IE_WR_RESP_CNT_OVFL_EN_FLDSHFT (5)
#define HWIO_PRMU_IE_WR_REQ_CNT_OVFL_EN_FLDMASK (0x10)
#define HWIO_PRMU_IE_WR_REQ_CNT_OVFL_EN_FLDSHFT (4)
#define HWIO_PRMU_IE_WR_REQ_LEN_OVFL_EN_FLDMASK (0x8)
#define HWIO_PRMU_IE_WR_REQ_LEN_OVFL_EN_FLDSHFT (3)
#define HWIO_PRMU_IE_RD_RESP_CNT_OVFL_EN_FLDMASK (0x4)
#define HWIO_PRMU_IE_RD_RESP_CNT_OVFL_EN_FLDSHFT (2)
#define HWIO_PRMU_IE_RD_REQ_CNT_OVFL_EN_FLDMASK (0x2)
#define HWIO_PRMU_IE_RD_REQ_CNT_OVFL_EN_FLDSHFT (1)
#define HWIO_PRMU_IE_RD_REQ_LEN_OVFL_EN_FLDMASK (0x1)
#define HWIO_PRMU_IE_RD_REQ_LEN_OVFL_EN_FLDSHFT (0)

#define HWIO_PRMU_IS_REGOFF 0x0C
#define HWIO_PRMU_IS_ADDR(bAddr, regX) (bAddr + HWIO_PRMU_IS_REGOFF)
#define HWIO_PRMU_IS_RSVD0_FLDMASK (0xffffffc0)
#define HWIO_PRMU_IS_RSVD0_FLDSHFT (6)
#define HWIO_PRMU_IS_WR_RESP_CNT_OVFL_STS_FLDMASK (0x20)
#define HWIO_PRMU_IS_WR_RESP_CNT_OVFL_STS_FLDSHFT (5)
#define HWIO_PRMU_IS_WR_REQ_CNT_OVFL_STS_FLDMASK (0x10)
#define HWIO_PRMU_IS_WR_REQ_CNT_OVFL_STS_FLDSHFT (4)
#define HWIO_PRMU_IS_WR_REQ_LEN_OVFL_STS_FLDMASK (0x8)
#define HWIO_PRMU_IS_WR_REQ_LEN_OVFL_STS_FLDSHFT (3)
#define HWIO_PRMU_IS_RD_RESP_CNT_OVFL_STS_FLDMASK (0x4)
#define HWIO_PRMU_IS_RD_RESP_CNT_OVFL_STS_FLDSHFT (2)
#define HWIO_PRMU_IS_RD_REQ_CNT_OVFL_STS_FLDMASK (0x2)
#define HWIO_PRMU_IS_RD_REQ_CNT_OVFL_STS_FLDSHFT (1)
#define HWIO_PRMU_IS_RD_REQ_LEN_OVFL_STS_FLDMASK (0x1)
#define HWIO_PRMU_IS_RD_REQ_LEN_OVFL_STS_FLDSHFT (0)

#define HWIO_PRMU_LAT_CURMIN_REGNUM 14
#define HWIO_PRMU_LAT_CURMIN_REGOFF 0x10
#define HWIO_PRMU_LAT_CURMIN_ADDR(bAddr, regX) \
	(((regX >= 0) && (regX < HWIO_PRMU_LAT_CURMIN_REGNUM)) ? \
	(bAddr + HWIO_PRMU_LAT_CURMIN_REGOFF + (regX * 4)) : MNH_BAD_ADDR)
#define HWIO_PRMU_LAT_CURMIN_LAT_MIN_FLDMASK (0xffff0000)
#define HWIO_PRMU_LAT_CURMIN_LAT_MIN_FLDSHFT (16)
#define HWIO_PRMU_LAT_CURMIN_LAT_CUR_FLDMASK (0xffff)
#define HWIO_PRMU_LAT_CURMIN_LAT_CUR_FLDSHFT (0)

#define HWIO_PRMU_LAT_MAXAVG_REGNUM 14
#define HWIO_PRMU_LAT_MAXAVG_REGOFF 0x14
#define HWIO_PRMU_LAT_MAXAVG_ADDR(bAddr, regX) \
	(((regX >= 0) && (regX < HWIO_PRMU_LAT_MAXAVG_REGNUM)) ? \
	(bAddr + HWIO_PRMU_LAT_MAXAVG_REGOFF + (regX * 4)) : MNH_BAD_ADDR)
#define HWIO_PRMU_LAT_MAXAVG_LAT_AVG_FLDMASK (0xffff0000)
#define HWIO_PRMU_LAT_MAXAVG_LAT_AVG_FLDSHFT (16)
#define HWIO_PRMU_LAT_MAXAVG_LAT_MAX_FLDMASK (0xffff)
#define HWIO_PRMU_LAT_MAXAVG_LAT_MAX_FLDSHFT (0)

#define HWIO_PRMU_LAT_ADDR_REGNUM 15
#define HWIO_PRMU_LAT_ADDR_REGOFF 0x18
#define HWIO_PRMU_LAT_ADDR_ADDR(bAddr, regX) \
	(((regX >= 0) && (regX < HWIO_PRMU_LAT_ADDR_REGNUM)) ? \
	(bAddr + HWIO_PRMU_LAT_ADDR_REGOFF + (regX * 4)) : MNH_BAD_ADDR)
#define HWIO_PRMU_LAT_ADDR_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_LAT_ADDR_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_LAT_ADDR_ADDR_FLDMASK (0xfffff)
#define HWIO_PRMU_LAT_ADDR_ADDR_FLDSHFT (0)

#define HWIO_PRMU_CNT_LO_REGNUM 19
#define HWIO_PRMU_CNT_LO_REGOFF 0x30
#define HWIO_PRMU_CNT_LO_ADDR(bAddr, regX) \
	(((regX >= 0) && (regX < HWIO_PRMU_CNT_LO_REGNUM)) ? \
	(bAddr + HWIO_PRMU_CNT_LO_REGOFF + (regX * 4)) : MNH_BAD_ADDR)
#define HWIO_PRMU_CNT_LO_CNT_FLDMASK (0xffffffff)
#define HWIO_PRMU_CNT_LO_CNT_FLDSHFT (0)

#define HWIO_PRMU_CNT_HI_REGNUM 16
#define HWIO_PRMU_CNT_HI_REGOFF 0x40
#define HWIO_PRMU_CNT_HI_ADDR(bAddr, regX) \
	(((regX >= 0) && (regX < HWIO_PRMU_CNT_HI_REGNUM)) ? \
	(bAddr + HWIO_PRMU_CNT_HI_REGOFF + (regX * 4)) : MNH_BAD_ADDR)
#define HWIO_PRMU_CNT_HI_RSVD0_FLDMASK (0xfff00000)
#define HWIO_PRMU_CNT_HI_RSVD0_FLDSHFT (20)
#define HWIO_PRMU_CNT_HI_CNT_FLDMASK (0xfffff)
#define HWIO_PRMU_CNT_HI_CNT_FLDSHFT (0)

#endif // __MNH_HWIO_PRMU_
