#
# Makefile for paintbox programmable IPU.
#

obj-$(CONFIG_PAINTBOX)				+= paintbox.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma.o
obj-$(CONFIG_PAINTBOX_FPGA_SUPPORT)		+= paintbox-dma-fpga.o
obj-$(CONFIG_PAINTBOX_SIMULATOR_SUPPORT)	+= paintbox-dma-sim.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-io.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-lbp.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-stp.o
obj-$(CONFIG_PAINTBOX_SIMULATOR_SUPPORT)	+= paintbox-stp-sim.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-utils.o
