#
# Makefile for paintbox programmable IPU.
#

obj-$(CONFIG_PAINTBOX)				+= paintbox.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-debug.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-dma-sim.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-io.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-lbp.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-mipi.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-sram.o
obj-$(CONFIG_PAINTBOX)				+= paintbox-stp.o
obj-$(CONFIG_PAINTBOX_SIMULATOR_SUPPORT)	+= paintbox-stp-sim.o
